### ISSUE TITLE
as_hashmap->set collision handling

### ISSUE THREAD

**Issue by aaloanm** [aerospike/aerospike-common#2]
Hello,

as_hashmap's set function maps the hash of a key to it's value. This is fine for numeric values, however, there would be collisions for string values, resulting in lost data.

For example,

``` c
as_val k1, v1;
as_val k2, v2;
/* .. init k1 & k2 as strings of unique uuids .. */
as_hashmap x;
/* .. init x .. */
as_hashmap_set(&x, &k1, &v1); /* (1) */
as_hashmap_set(&x, &k2, &v2); /* (2) */
```

Assuming the hash code function for k1 and k2 return the same /hash/ value, as_hashmap_set will, internally, remove the mapping for k1, even though it has a unique /value/, to make room for k2.

Is this condition, especially for UDFs that produce maps with string keys as result, handled elsewhere or is this an actual issue?

Thanks,
Aaloan

**Comment by wchu-citrusleaf** [comment]
This is an issue for non-integer keys. We have on our task list to provide a better hashmap implementation.

**Comment by aaloanm** [comment]
Im currently replacing the dependency on shash in the lua wrapper to an open hash map impl, which would fix the issue and improve performance. Are there any requirements for creating a pull request?

Sent from MailWise

-------- Original Message --------

**Comment by wchu-citrusleaf** [comment]
No special requirements for the pull request. We will evaluate the open hashmap implementation.
